# Generated by Django 2.1.1 on 2018-10-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertest',
            name='user_inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.UserInquirer'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Category'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.UserTest'),
        ),
        migrations.AddField(
            model_name='userinquirer',
            name='inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Inquirer'),
        ),
        migrations.AddField(
            model_name='userinquirer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Answer'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.UserQuestion'),
        ),
        migrations.AddField(
            model_name='test',
            name='inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='testing.Inquirer'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='testing.Test'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.Question'),
        ),
    ]
