# Generated by Django 2.1.1 on 2018-10-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20181022_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.UserTest'),
        ),
    ]
