# Generated by Django 2.1.1 on 2018-10-28 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20181027_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquirer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inquirer', to=settings.AUTH_USER_MODEL),
        ),
    ]
