# Generated by Django 2.1.1 on 2018-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_auto_20181028_1525'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useranswer',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
