export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN_ERROR_SERVER = 'LOG_IN_ERROR_SERVER';

export const INQUIRER_REQUEST = 'INQUIRER_REQUEST';
export const INQUIRER_SUCCESS = 'INQUIRER_SUCCESS';
export const INQUIRER_ERROR_SERVER = 'INQUIRER_ERROR_SERVER';
export const INQUIRER_ADD = 'INQUIRER_ADD';
export const INQUIRER_DELETE_TEST = 'INQUIRER_DELETE_TEST';
export const INQUIRER_DELETE_CATEGORY = 'INQUIRER_DELETE_CATEGORY';
export const INQUIRER_DELETE_INQUIRER = 'INQUIRER_DELETE_INQUIRER';
export const INQUIRER_DELETE_QUESTION = 'INQUIRER_DELETE_QUESTION';
export const INQUIRER_ADD_QUESTION = 'INQUIRER_ADD_QUESTION';
export const INQUIRER_NOT_ALL_DATA = 'INQUIRER_NOT_ALL_DATA';
export const INQUIRER_SAVE_INQUIRER_SUCCESS = 'INQUIRER_SAVE_INQUIRER_SUCCESS';
export const INQUIRER_SAVE_INQUIRER_ERROR = 'INQUIRER_SAVE_INQUIRER_ERROR';
export const INQUIRER_SAVE_TEST_SUCCESS = 'INQUIRER_SAVE_TEST_SUCCESS';
export const INQUIRER_NOT_ALL_VALID_DATA_TEST = 'INQUIRER_NOT_ALL_VALID_DATA_TEST';
export const INQUIRER_SAVE_CATEGORY_SUCCESS = 'INQUIRER_SAVE_CATEGORY_SUCCESS';
export const INQUIRER_NOT_VALID_DATA_CATEGORY = 'INQUIRER_NOT_VALID_DATA_CATEGORY';
export const INQUIRER_NOT_FOUND_USER_FILE = 'INQUIRER_NOT_FOUND_USER_FILE';
export const INQUIRER_DOWNLOAD_USER_DATA_SUCCESS = 'INQUIRER_DOWNLOAD_USER_DATA_SUCCESS';
export const INQUIRER_IS_NOT_VALID_TIME = 'INQUIRER_IS_NOT_VALID_TIME';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_ERROR_SERVER = 'QUESTION_ERROR_SERVER';
export const QUESTION_CHANGE_TITLE = 'QUESTION_CHANGE_TITLE';
export const QUESTION_CHANGE_TYPE = 'QUESTION_CHANGE_TYPE';
export const QUESTION_ADD_ITEM = 'QUESTION_ADD_ITEM';
export const QUESTION_DELETE_ITEM = 'QUESTION_DELETE_ITEM';
export const QUESTION_CHANGE_ANSWER_ITEM = 'QUESTION_CHANGE_ANSWER_ITEM';
export const QUESTION_CHANGE_SCORE_ITEM = 'QUESTION_CHANGE_SCORE_ITEM';
export const QUESTION_SET_EMPTY_QUESTION = 'QUESTION_SET_EMPTY_QUESTION';
export const QUESTION_SET_ANSWER = 'QUESTION_SET_ANSWER';
export const QUESTION_SAVE_SUCCESS = 'QUESTION_SAVE_SUCCESS';
export const QUESTION_NOT_VALID = 'QUESTION_NOT_VALID';
export const TEST_ADD_SUCCESS = 'TEST_ADD_SUCCESS';
export const QUESTION_CHANGE_CHECKBOX = 'QUESTION_CHANGE_CHECKBOX';

export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';

export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS';

export const RESULT_REQUEST = 'RESULT_REQUEST';
export const RESULT_SUCCESS = 'RESULT_SUCCESS';
export const RESULT_ERROR_SERVER = 'RESULT_ERROR_SERVER';
export const RESULT_GET_INQUIRERS_SUCCESS = 'RESULT_GET_INQUIRERS_SUCCESS';
export const RESULT_GET_RESULT_FOR_INQUIRER = 'RESULT_GET_RESULT_FOR_INQUIRER';
export const RESULT_CHANGE_VISIBLE_COLLAPSIBLE = 'RESULT_CHANGE_VISIBLE_COLLAPSIBLE';
export const RESULT_LOADING_RESULT = 'RESULT_LOADING_RESULT';

export const REVIEW_GET_INQUIRERS = 'REVIEW_GET_INQUIRERS';
export const REVIEW_LOADING_REVIEW = 'REVIEW_LOADING_REVIEW';
export const REVIEW_CHANGE_VISIBLE_COLLAPSIBLE = 'REVIEW_CHANGE_VISIBLE_COLLAPSIBLE';
export const REVIEW_GET_ANSWER = 'REVIEW_GET_ANSWER';
export const REVIEW_CHANGE_SCORE = 'REVIEW_CHANGE_SCORE';
export const REVIEW_SAVE_SCORE = 'REVIEW_SAVE_SCORE';
