version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    environment:
    - DJANGO_SETTINGS_MODULE=application.settings_prod
    - DEBUG=True
    - DB_NAME=test
    - DB_USER=test
    - DB_PASSWORD=test
    - DB_HOST=database
    - DB_PORT=5432
    - EMAIL_HOST=devmail
    - EMAIL_PORT=25
    - HOST_URL=http://ltptest.local
    - FROM_EMAIL=admin@local
    depends_on:
    - database
    - redis
    command: 'pytest'

  redis:
    image: redis:4.0.11

  devmail:
    image: djfarrelly/maildev

  database:
    image: postgres:10.5
    hostname: database
    restart: always
    volumes:
      - /tmp/test-utility-backend/postgresql:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=test
