export const TEST_REQUEST = 'TEST_REQUEST';
export const TEST_SUCCESS = 'TEST_SUCCESS';
export const TEST_FAILURE = 'TEST_FAILURE';
export const SET_TEST_TITLE = 'SET_TEST_TITLE';
export const SET_TEST_FINISH = 'SET_TEST_FINISH';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_FAILURE = 'QUESTION_FAILURE';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_REQUEST_CHECK = 'USER_REQUEST_CHECK';
export const USER_SET_USER_INFO = 'USER_SET_USER_INFO';

export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';

export const QUESTION_SET_FIRST_SUCCESS = 'QUESTION_SET_FIRST_SUCCESS';
export const QUESTION_SET_NEW_QUESTION = 'QUESTION_SET_NEW_QUESTION';
export const QUESTION_FINISH_TEST = 'QUESTION_FINISH_TEST';

export const SHOW_SERVER_ERROR = 'SHOW_SERVER_ERROR';
