# Generated by Django 2.1.1 on 2018-10-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inviter', '0001_initial'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitejob',
            name='inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Inquirer'),
        ),
    ]
