# Generated by Django 2.1.1 on 2018-10-23 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviter', '0002_invitejob_inquirer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitejob',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invitejob',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
